version: '2.2'

networks:
  npm:
    external: true
  overleaf:

services:
  sharelatex:
    restart: always
    image: sharelatex/sharelatex
    container_name: sharelatex
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    links:
      - mongo
      - redis
    volumes:
      - ~/sharelatex_data:/var/lib/sharelatex
    networks:
      - npm
      - overleaf
    environment:
        SHARELATEX_APP_NAME: Overcomplicated
        SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
        SHARELATEX_REDIS_HOST: redis
        REDIS_HOST: redis
        ENABLED_LINKED_FILE_TYPES: 'project_file,project_output_file'
        # Enables Thumbnail generation using ImageMagick
        ENABLE_CONVERSIONS: 'true'
        # Disables email confirmation requirement
        EMAIL_CONFIRMATION_DISABLED: 'false'
        # temporary fix for LuaLaTex compiles
        # see https://github.com/overleaf/overleaf/issues/695
        TEXMFVAR: /var/lib/sharelatex/tmp/texmf-var

  mongo:
    restart: always
    image: mongo:4.0
    container_name: mongo
    expose:
      - 27017
    volumes:
      - ~/mongo_data:/data/db
    networks:
      - overleaf
    healthcheck:
        test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
        interval: 10s
        timeout: 10s
        retries: 5

  redis:
    restart: always
    image: redis:5
    container_name: redis
    expose:
        - 6379
    volumes:
      - ~/redis_data:/data
    networks:
      - overleaf