version: '3.3'

volumes:
  tailscale-data:
  npm-data:
  npm-ssl:
    external: true
  npm-db:
  nextcloud-app:
  nextcloud-data:
    external: true
  nextcloud-db:
  yourls-conf:
  yourls-db:

networks:
  nextcloud:
  yourls:
  npm:

services:
  tailscale:
    container_name: tailscale
    hostname: $HOSTNAME
      # This will become the tailscale device name
    image: richnorth/tailscale:v0.99.1
    volumes:
        - tailscale-data:/var/lib
          # State data will be stored in this directory
        - /dev/net/tun:/dev/net/tun
          # Required for tailscale to work
    cap_add:                                    
      # Required for tailscale to work
      - net_admin
      - sys_module
    command: tailscaled 
    ports:
      - '80:80'
      - '443:443'
    networks:
      - nextcloud
      - yourls
      - npm

  npm-app:
    container_name: npm-app
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    environment:
      DB_MYSQL_PASSWORD: $NPM_DATABASE_PASSWORD
      DB_MYSQL_NAME: npm
      DB_MYSQL_USER: npm
      DB_MYSQL_HOST: npm-db
      DB_MYSQL_PORT: 3306
    volumes:
      - npm-data:/data
      - npm-ssl:/etc/letsencrypt
    network_mode: service:tailscale
    depends_on:
      - npm-db

  npm-db:
    container_name: npm-db
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $NPM_DATABASE_ROOT_PASSWORD
      MYSQL_DATABASE: npm
      MYSQL_USER: npm
      MYSQL_PASSWORD: $NPM_DATABASE_PASSWORD
    volumes:
      - npm-db:/var/lib/mysql
    networks:
      - npm

  nextcloud-app:
    container_name: nextcloud-app
    image: nextcloud
    restart: always
    volumes:
      - nextcloud-app:/var/www/html
      - nextcloud-data:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=$NEXTCLOUD_DATABASE_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
    networks:
      - nextcloud
    depends_on:
      - nextcloud-db
      - npm-app

  nextcloud-db:
    container_name: nextcloud-db
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$NEXTCLOUD_DATABASE_ROOT_PASSWORD
      - MYSQL_PASSWORD=$NEXTCLOUD_DATABASE_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - nextcloud
  
  yourls-app:
    container_name: yourls-app
    hostname: $YOURLS_HOSTNAME
    image: yourls
    restart: always
    volumes:
      - yourls-conf:/var/www/html/user
    environment:
      YOURLS_SITE: https://$YOURLS_HOSTNAME
      YOURLS_USER: $YOURLS_ADMIN_USERNAME
      YOURLS_PASS: $YOURLS_ADMIN_PASSWORD
      YOURLS_DB_PASS: $YOURLS_DATABASE_PASSWORD
      YOURLS_DB_HOST: yourls-db
    networks:
      - yourls
    depends_on:
      - yourls-db
      - npm-app

  yourls-db:
    container_name: yourls-db
    image: mysql
    restart: always
    volumes:
      - yourls-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $YOURLS_DATABASE_PASSWORD
      MYSQL_DATABASE: yourls
    networks:
      - yourls
